import React from 'react';
import { AppConfig, AppID } from './types';
import {
  UserCircle,
  IdentificationCard,
  ChatTeardrop,
  UsersThree,
  GearSix,
  Images,
  PaintBrush,
  Palette,
  Heart,
  BookOpenText,
  SealCheck,
  House,
  DeviceMobileCamera,
  Fire,
  Books,
  Question,
  GameController,
  Globe,
  PenNib,
  PiggyBank,
  Compass,
  Sparkle,
  GlobeSimple,
  MusicNotes,
  PhoneCall,
  Crosshair,
  Smiley,
  ImageSquare,
  TrayArrowDown,
  CalendarDots,
  MagicWand,
} from '@phosphor-icons/react';

// SVG 图标库 - Phosphor Icons
export const Icons: Record<string, React.FC<{ className?: string }>> = {
  Character: ({ className }) => <UserCircle className={className} weight="bold" />,
  User: ({ className }) => <IdentificationCard className={className} weight="bold" />,
  Chat: ({ className }) => <ChatTeardrop className={className} weight="bold" />,
  GroupChat: ({ className }) => <UsersThree className={className} weight="bold" />,
  Settings: ({ className }) => <GearSix className={className} weight="bold" />,
  Gallery: ({ className }) => <Images className={className} weight="bold" />,
  ThemeMaker: ({ className }) => <PaintBrush className={className} weight="bold" />,
  Appearance: ({ className }) => <Palette className={className} weight="bold" />,
  Date: ({ className }) => <Heart className={className} weight="bold" />,
  Journal: ({ className }) => <BookOpenText className={className} weight="bold" />,
  Schedule: ({ className }) => <SealCheck className={className} weight="bold" />,
  CompanionPlan: ({ className }) => <Compass className={className} weight="bold" />,
  Room: ({ className }) => <House className={className} weight="bold" />,
  CheckPhone: ({ className }) => <DeviceMobileCamera className={className} weight="bold" />,
  Social: ({ className }) => <Fire className={className} weight="bold" />,
  Study: ({ className }) => <Books className={className} weight="bold" />,
  FAQ: ({ className }) => <Question className={className} weight="bold" />,
  Game: ({ className }) => <GameController className={className} weight="bold" />,
  Worldbook: ({ className }) => <Globe className={className} weight="bold" />,
  Novel: ({ className }) => <PenNib className={className} weight="bold" />,
  Bank: ({ className }) => <PiggyBank className={className} weight="bold" />,
  SpecialMoments: ({ className }) => <Sparkle className={className} weight="bold" />,
  Browser: ({ className }) => <GlobeSimple className={className} weight="bold" />,
  Songwriting: ({ className }) => <MusicNotes className={className} weight="bold" />,
  Call: ({ className }) => <PhoneCall className={className} weight="bold" />,
  Guidebook: ({ className }) => <Crosshair className={className} weight="bold" />,
  LifeSim: ({ className }) => <Smiley className={className} weight="bold" />,
  Widget: ({ className }) => <ImageSquare className={className} weight="bold" />,
  HistoryImport: ({ className }) => <TrayArrowDown className={className} weight="bold" />,
  DailyArchive: ({ className }) => <CalendarDots className={className} weight="bold" />,
  CreativeScheme: ({ className }) => <MagicWand className={className} weight="bold" />,
};

export const INSTALLED_APPS: AppConfig[] = [
  { id: AppID.Character, name: '通讯录', icon: 'Character', color: 'indigo' },
  { id: AppID.Chat, name: 'Message', icon: 'Chat', color: 'green' },
  { id: AppID.Call, name: '电话', icon: 'Call', color: 'emerald' },
  { id: AppID.Room, name: '小小窝', icon: 'Room', color: 'rose' },
  { id: AppID.GroupChat, name: '群聊', icon: 'GroupChat', color: 'violet' },
  { id: AppID.Journal, name: '交换日记', icon: 'Journal', color: 'amber' },
  { id: AppID.CompanionPlan, name: '同行计划', icon: 'CompanionPlan', color: 'emerald' },
  { id: AppID.Schedule, name: '时光簿', icon: 'Schedule', color: 'cyan' },
  { id: AppID.DailyArchive, name: '对话日历', icon: 'DailyArchive', color: 'violet' },
  { id: AppID.Study, name: '书房', icon: 'Study', color: 'emerald' },
  { id: AppID.Social, name: '朋友圈', icon: 'Social', color: 'red' },
  { id: AppID.User, name: '档案', icon: 'User', color: 'blue' },
  { id: AppID.Gallery, name: '相册', icon: 'Gallery', color: 'orange' },

  { id: AppID.CheckPhone, name: '查手机', icon: 'CheckPhone', color: 'slate' },
  // { id: AppID.Browser, name: '浏览器', icon: 'Browser', color: 'blue' }, // Hidden
  { id: AppID.Date, name: '见面', icon: 'Date', color: 'pink' },
  { id: AppID.Guidebook, name: '攻略本', icon: 'Guidebook', color: 'slate' },
  { id: AppID.LifeSim, name: '都市人生', icon: 'LifeSim', color: 'purple' },
  { id: AppID.Game, name: 'TRPG', icon: 'Game', color: 'orange' },
  { id: AppID.Worldbook, name: '世界书', icon: 'Worldbook', color: 'indigo' },
  { id: AppID.SpecialMoments, name: '特别时光', icon: 'SpecialMoments', color: 'pink' },

  { id: AppID.ThemeMaker, name: '聊天装扮', icon: 'ThemeMaker', color: 'purple' },
  { id: AppID.Appearance, name: '外观', icon: 'Appearance', color: 'slate' },
  { id: AppID.Widget, name: '小组件', icon: 'Widget', color: 'cyan' },
  {
    id: AppID.HistoryImport,
    name: '旧日迁入',
    icon: 'HistoryImport',
    color: 'violet',
  },
  { id: AppID.Novel, name: '手稿', icon: 'Novel', color: 'amber' },
  { id: AppID.CreativeScheme, name: '创作方案', icon: 'CreativeScheme', color: 'violet' },
  { id: AppID.Songwriting, name: '写歌', icon: 'Songwriting', color: 'fuchsia' },
  { id: AppID.Bank, name: '存钱罐', icon: 'Bank', color: 'lime' },
  { id: AppID.FAQ, name: '使用帮助', icon: 'FAQ', color: 'indigo' },
  { id: AppID.Settings, name: '设置', icon: 'Settings', color: 'slate' },
];

export const DOCK_APPS = [AppID.Chat, AppID.Call, AppID.Gallery, AppID.Settings];

export const LAUNCHER_APP_GROUPS = [
  {
    id: 'companion',
    title: '日常陪伴核心',
    appIds: [
      AppID.Character,
      AppID.CompanionPlan,
      AppID.Schedule,
      AppID.Social,
      AppID.Journal,
      AppID.Study,
      AppID.GroupChat,
      AppID.User,
    ],
  },
  {
    id: 'relationship-life',
    title: '关系与共同生活',
    appIds: [
      AppID.Date,
      AppID.Room,
      AppID.CheckPhone,
      AppID.SpecialMoments,
      AppID.DailyArchive,
      AppID.HistoryImport,
    ],
  },
  {
    id: 'story-creation',
    title: '独立故事创作',
    appIds: [
      AppID.Novel,
      AppID.Worldbook,
      AppID.CreativeScheme,
      AppID.Game,
      AppID.LifeSim,
      AppID.Guidebook,
      AppID.Songwriting,
    ],
  },
  {
    id: 'decoration-tools',
    title: '装扮与工具',
    appIds: [
      AppID.ThemeMaker,
      AppID.Appearance,
      AppID.Widget,
      AppID.Bank,
      AppID.FAQ,
    ],
  },
];
